package runner

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/Nano-AI/leetui/internal/workspace"
)

const (
	cppHeaderFile = "leetui_driver.h"
	cppMainFile   = "leetui_main.cpp"
)

// cppBuilders maps a metaData type to the header function that builds it and the C++
// type it produces.
//
// Unknown types are an error rather than a guess: a wrong guess compiles into a driver
// that decodes garbage, whereas an error routes the problem to the judge, which is
// always correct if slower.
var cppBuilders = map[string][2]string{
	"integer": {"int", "toInt"}, "int": {"int", "toInt"},
	"long":   {"long long", "toLong"},
	"double": {"double", "toDouble"}, "float": {"double", "toDouble"},
	"boolean":   {"bool", "toBool"},
	"string":    {"std::string", "toString"},
	"character": {"char", "toChar"},

	"integer[]":       {"std::vector<int>", "toIntVector"},
	"list<integer>":   {"std::vector<int>", "toIntVector"},
	"double[]":        {"std::vector<double>", "toDoubleVector"},
	"list<double>":    {"std::vector<double>", "toDoubleVector"},
	"boolean[]":       {"std::vector<bool>", "toBoolVector"},
	"list<boolean>":   {"std::vector<bool>", "toBoolVector"},
	"string[]":        {"std::vector<std::string>", "toStringVector"},
	"list<string>":    {"std::vector<std::string>", "toStringVector"},
	"character[]":     {"std::vector<char>", "toCharVector"},
	"list<character>": {"std::vector<char>", "toCharVector"},

	"integer[][]":           {"std::vector<std::vector<int>>", "toIntGrid"},
	"list<list<integer>>":   {"std::vector<std::vector<int>>", "toIntGrid"},
	"character[][]":         {"std::vector<std::vector<char>>", "toCharGrid"},
	"list<list<character>>": {"std::vector<std::vector<char>>", "toCharGrid"},
	"string[][]":            {"std::vector<std::vector<std::string>>", "toStringGrid"},
	"list<list<string>>":    {"std::vector<std::vector<std::string>>", "toStringGrid"},

	"ListNode": {"ListNode*", "toList"},
	"TreeNode": {"TreeNode*", "toTree"},
}

func cppType(t string) (cType, builder string, err error) {
	pair, ok := cppBuilders[strings.TrimSpace(t)]
	if !ok {
		return "", "", fmt.Errorf("no C++ type for metaData type %q", t)
	}
	return pair[0], pair[1], nil
}

// generateCpp writes the header and a main() that decodes arguments and calls Solution.
func (l *Local) generateCpp(p Problem, meta Meta, dir string) error {
	// The header is identical for every problem, so it lives once in the workspace's
	// globals/ directory rather than beside every solution (D-029).
	if err := writeGlobalDriver(dir, cppHeaderFile, "drivers/cpp/driver.h"); err != nil {
		return err
	}
	// A folder created before the driver moved still says #include "leetui_driver.h".
	if err := migrateInclude(dir, cppHeaderFile); err != nil {
		return err
	}

	var decls, args strings.Builder
	for i, param := range meta.Params {
		cType, builder, err := cppType(param.Type)
		if err != nil {
			return err
		}
		fmt.Fprintf(&decls, "    %s a%d = leetui::%s(leetui::parse(lines[%d]));\n",
			cType, i, builder, i)
		if i > 0 {
			args.WriteString(", ")
		}
		fmt.Fprintf(&args, "a%d", i)
	}

	rule := RuleFor(p.Slug)
	var call string
	switch {
	case rule.MutatesArg >= 0:
		if rule.MutatesArg >= len(meta.Params) {
			return fmt.Errorf("override for %s names argument %d but there are %d",
				p.Slug, rule.MutatesArg, len(meta.Params))
		}
		call = fmt.Sprintf(
			"    auto n = sol.%s(%s);\n"+
				"    std::cout << leetui::dump(leetui::prefix(a%d, (int)n)) << std::endl;\n",
			meta.Name, args.String(), rule.MutatesArg)
	case meta.Return.Type == "void":
		call = fmt.Sprintf("    sol.%s(%s);\n    std::cout << \"null\" << std::endl;\n",
			meta.Name, args.String())
	default:
		call = fmt.Sprintf("    std::cout << leetui::dump(sol.%s(%s)) << std::endl;\n",
			meta.Name, args.String())
	}

	main := fmt.Sprintf(`// Generated by leetui. Edit solution.cpp, not this file.
#include "%s"
#include "solution.cpp"

int main() {
    std::ios::sync_with_stdio(false);
    auto lines = leetui::readLines(%d);
    (void)lines;

    Solution sol;
%s%s    return 0;
}
`, workspace.GlobalRef(cppHeaderFile), len(meta.Params), decls.String(), call)

	if err := os.WriteFile(filepath.Join(dir, cppMainFile), []byte(main), 0o644); err != nil {
		return fmt.Errorf("write cpp main: %w", err)
	}
	return nil
}

// runCpp compiles once, then runs each case against the built binary.
func (l *Local) runCpp(ctx context.Context, dir string, cases []TestCase, rule Rule) (Result, error) {
	bin := filepath.Join(dir, "leetui_bin")

	// -Werror=return-type, and deliberately NOT -w.
	//
	// -w was here to quiet warnings from LeetCode's starter code. Measured, that code
	// produces none — but -w also beat -Wreturn-type, so a half-written solution with no
	// return statement compiled clean and died at runtime as "signal: bus error". That is
	// undefined behaviour reported as a mystery, in the exact situation where the user is
	// mid-solution and most needs a straight answer.
	//
	// Order matters: -w anywhere on this line would silently cancel the -Werror.
	//
	// Nothing broader than this is enabled. -Wall over someone's in-progress solution is
	// noise they did not ask leetui to have opinions about.
	build := exec.CommandContext(ctx, "c++", "-std=c++17", "-O2", "-Werror=return-type",
		"-o", bin, cppMainFile)
	build.Dir = dir
	var buildErr bytes.Buffer
	build.Stderr = &buildErr

	if err := build.Run(); err != nil {
		msg := strings.TrimSpace(buildErr.String())
		if msg == "" {
			msg = err.Error()
		}
		return Result{CompileErr: msg}, nil
	}
	defer os.Remove(bin)

	started := time.Now()
	result := Result{Cases: make([]CaseResult, 0, len(cases))}
	for _, tc := range cases {
		if err := ctx.Err(); err != nil {
			return result, err
		}
		result.Cases = append(result.Cases, l.runBinaryCase(ctx, dir, bin, nil, tc, rule))
	}
	result.Elapsed = time.Since(started)
	return result, nil
}
