package runner

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// JavaScript and TypeScript.
//
// D-004 said JS/TS was the cheap one to add after the first three, and it was: the
// language is JSON-native, so the whole serialization layer the C++ driver needs is one
// call to JSON.parse.
//
// The one wrinkle is that LeetCode's JS starter has NO EXPORTS. It declares a bare
//
//	var twoSum = function(nums, target) { ... };
//
// and relies on the judge having defined ListNode and TreeNode as globals. So rather than
// import the solution, leetui CONCATENATES the driver, the solution, and a call into one
// file and runs that. The solution's function is then simply in scope, and the driver's
// ListNode/TreeNode are the globals it expects — the same arrangement the C++ driver has.
//
// Concatenation also makes TypeScript free. Node strips types across the whole file, so
// solution.ts runs exactly the way solution.js does with no transpile step, no tsconfig,
// and no second toolchain.

const jsEntryFile = "_leetui_run"

// jsExt is the extension the generated entry takes, which must match the solution's:
// Node decides whether to strip types by the file's own extension.
func jsExt(lang Lang) string {
	if lang.Slug == "typescript" {
		return ".ts"
	}
	return ".js"
}

// generateJS writes the single concatenated file that gets executed.
func (l *Local) generateJS(p Problem, meta Meta, lang Lang, dir string) error {
	driver, err := drivers.ReadFile("drivers/javascript/driver.js")
	if err != nil {
		return fmt.Errorf("read embedded javascript driver: %w", err)
	}

	solution, err := os.ReadFile(filepath.Join(dir, lang.Filename()))
	if err != nil {
		return fmt.Errorf("read solution: %w", err)
	}

	call, err := jsInvocation(p, meta)
	if err != nil {
		return err
	}

	var b strings.Builder
	b.WriteString("// Generated by leetui. Edit " + lang.Filename() + ", not this file.\n")
	b.Write(driver)
	b.WriteString("\n// ---- solution ----\n")
	b.Write(solution)
	b.WriteString("\n// ---- entry ----\n")
	b.WriteString(call)

	path := filepath.Join(dir, jsEntryFile+jsExt(lang))
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("write javascript entry: %w", err)
	}
	return nil
}

// jsInvocation builds the line that calls the solution.
func jsInvocation(p Problem, meta Meta) (string, error) {
	if meta.IsDesign() {
		methods, err := meta.DesignMethods()
		if err != nil {
			return "", err
		}
		byMethod := map[string][]string{}
		for _, m := range methods {
			ts := make([]string, 0, len(m.Params))
			for _, param := range m.Params {
				ts = append(ts, param.Type)
			}
			byMethod[m.Name] = ts
		}

		types, err := json.Marshal(byMethod)
		if err != nil {
			return "", fmt.Errorf("encode method types: %w", err)
		}
		return fmt.Sprintf("__leetui.runDesign(%s, %s);\n", meta.Classname, string(types)), nil
	}

	types, err := json.Marshal(meta.ParamTypes())
	if err != nil {
		return "", fmt.Errorf("encode parameter types: %w", err)
	}

	// The answer for an in-place problem is a mutated argument, not the return value.
	mutates := "null"
	if rule := RuleFor(p.Slug); rule.MutatesArg >= 0 {
		mutates = fmt.Sprint(rule.MutatesArg)
	}
	return fmt.Sprintf("__leetui.run(%s, %s, %s, %q);\n",
		meta.Name, string(types), mutates, meta.Return.Type), nil
}

// runJS executes the generated entry once per case.
func (l *Local) runJS(ctx context.Context, dir string, lang Lang, cases []TestCase, rule Rule) (Result, error) {
	entry := jsEntryFile + jsExt(lang)
	if _, err := os.Stat(filepath.Join(dir, entry)); err != nil {
		return Result{}, fmt.Errorf("no generated entry point in %s: %w", dir, err)
	}

	started := time.Now()
	result := Result{Cases: make([]CaseResult, 0, len(cases))}
	for _, tc := range cases {
		if err := ctx.Err(); err != nil {
			return result, err
		}
		result.Cases = append(result.Cases,
			l.runBinaryCase(ctx, dir, "node", []string{entry}, tc, rule))
	}
	result.Elapsed = time.Since(started)
	return result, nil
}
