package runner

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

// Generated filenames. The leading underscore keeps them out of the way alphabetically
// and signals that they are machine-written, not the user's.
const (
	pyDriverFile = "_leetui_driver.py"
	pyEntryFile  = "_leetui_run.py"
)

// generatePython writes the vendored driver and an entry point wired to this problem's
// signature.
func (l *Local) generatePython(p Problem, meta Meta, dir string) error {
	driver, err := drivers.ReadFile("drivers/python3/driver.py")
	if err != nil {
		return fmt.Errorf("read embedded python driver: %w", err)
	}
	if err := os.WriteFile(filepath.Join(dir, pyDriverFile), driver, 0o644); err != nil {
		return fmt.Errorf("write python driver: %w", err)
	}

	types, err := json.Marshal(meta.ParamTypes())
	if err != nil {
		return fmt.Errorf("encode parameter types: %w", err)
	}

	// The answer for an in-place problem is a mutated argument, not the return value.
	mutates := "None"
	if rule := RuleFor(p.Slug); rule.MutatesArg >= 0 {
		mutates = fmt.Sprintf("%q", fmt.Sprint(rule.MutatesArg))
	}

	entry := fmt.Sprintf(`# Generated by leetui. Edit solution.py, not this file.
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from %s import run  # noqa: E402
from solution import Solution  # noqa: E402

run(Solution, %q, %s, mutates=%s)
`, strings.TrimSuffix(pyDriverFile, ".py"), meta.Name, string(types), mutates)

	if err := os.WriteFile(filepath.Join(dir, pyEntryFile), []byte(entry), 0o644); err != nil {
		return fmt.Errorf("write python entry point: %w", err)
	}
	return nil
}

// runPython executes each case in its own process.
//
// One process per case rather than one for all of them: a solution that crashes or loops
// forever then costs exactly one case instead of the whole run, and each case gets a
// clean interpreter with no state carried over from the last.
func (l *Local) runPython(ctx context.Context, dir string, cases []TestCase, rule Rule) (Result, error) {
	entry := filepath.Join(dir, pyEntryFile)
	if _, err := os.Stat(entry); err != nil {
		return Result{}, fmt.Errorf("no generated entry point in %s: %w", dir, err)
	}

	started := time.Now()
	result := Result{Cases: make([]CaseResult, 0, len(cases))}

	for _, tc := range cases {
		if err := ctx.Err(); err != nil {
			return result, err
		}
		result.Cases = append(result.Cases, l.runPythonCase(ctx, dir, entry, tc, rule))
	}

	result.Elapsed = time.Since(started)
	return result, nil
}

func (l *Local) runPythonCase(ctx context.Context, dir, entry string, tc TestCase, rule Rule) CaseResult {
	caseCtx, cancel := context.WithTimeout(ctx, l.timeout())
	defer cancel()

	// Arguments are passed as a slice, never interpolated into a shell string: the
	// problem slug and directory come from LeetCode and are not ours to trust.
	cmd := exec.CommandContext(caseCtx, "python3", entry)
	cmd.Dir = dir
	cmd.Stdin = strings.NewReader(tc.Input + "\n")

	var stdout, stderr bytes.Buffer
	cmd.Stdout, cmd.Stderr = &stdout, &stderr

	started := time.Now()
	err := cmd.Run()
	out := CaseResult{Case: tc, Elapsed: time.Since(started)}

	switch {
	case caseCtx.Err() == context.DeadlineExceeded:
		out.Err = fmt.Errorf("timed out after %s", l.timeout())
		return out
	case err != nil:
		// A traceback is far more useful than the exit status wrapping it.
		msg := strings.TrimSpace(stderr.String())
		if msg == "" {
			msg = err.Error()
		}
		out.Err = fmt.Errorf("%s", lastLines(msg, 6))
		return out
	}

	out.Actual = strings.TrimSpace(stdout.String())
	if tc.Expected != "" {
		out.Judged = true
		out.Passed = Compare(out.Actual, tc.Expected, rule)
	}
	return out
}

// lastLines keeps the tail of a traceback, where the actual exception lives.
func lastLines(s string, n int) string {
	lines := strings.Split(strings.TrimRight(s, "\n"), "\n")
	if len(lines) <= n {
		return s
	}
	return "…\n" + strings.Join(lines[len(lines)-n:], "\n")
}
